
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf # 配置文件挂载
      - ./html:/usr/share/nginx/html # 静态资源根目录挂载
      - ./log:/var/log/nginx # 日志文件挂载
      - ./ssl:/etc/nginx/ssl # ssl证书挂载
    networks:
      - mall_network
networks:
  mall_network:
    external:
      name: mall # 这里假设你的mall服务所在的网络叫
