version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --appendonly yes --requirepass "password"
    restart: always
    volumes:
      - ./data:/data #数据文件挂载
    ports:
      - 6379:6379
    networks:
      - mall_network
networks:
    default:
      external:
        name: mall
