services:
  minio:
    container_name: minio
    image: minio/minio
    hostname: "minio"
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    environment:
      MINIO_SERVER_URL: http://minio.chenlong.site
      MINIO_BROWSER_REDIRECT_URL: http://chenlong.site/minio/ui
      MINIO_ROOT_USER: minio    #管理后台用户名
      MINIO_ROOT_PASSWORD: password #管理后台密码，最小8个字符
    volumes:
      - ./data:/data               #映射当前目录下的data目录至容器内/data目录
      - ./.minio:/root/.minio   #映射配置目录
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    restart: always
    networks:
      - mall_network
networks:
  mall_network:
    external:
      name: mall
