version: '3.8'
services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./logs:/logs
      - ./data:/var/lib/mysql
    networks:
      - mall_network
networks:
  mall_network:
    external:
      name: mall
