server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://chenlong.site:3306/ry-cloud?serverTimezone=GMT%2b8
    password: mysqlcl.123456
    username: root
